#made this so that we can store all variables outside, so that we don't have to make any changes in components in future
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1--nNQUASb6QOvomGrbdIBigPS4910Upv/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion